os:
  - linux
  - osx

language: c
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then createdb travis; fi
  - psql -c 'create database jeremy;' -U `whoami`
script:
  - make CFLAGS="-fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all" test
  - make test-cpp
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make CFLAGS=-g valgrind; fi
addons:
  apt:
    packages:
      - apache2-utils
      - valgrind
      - libpq-dev
  homebrew:
    packages:
      - postgresql
      - libpq
services:
  - postgresql
